export const WS_MSG_EVENTS = {
    START_ROUND: 'WS_MSG_EVT_START_ROUND',
    ROUND_STARTED: 'WS_MSG_EVT_ROUND_STARTED',
    MASTER_JOIN_ROOM: 'WS_MSG_EVT_MASTER_JOIN_ROOM',
    MASTER_IS_PLAYING: 'WS_MSG_EVT_MASTER_IS_PLAYING',
    MASTER_JOINED_ROOM: 'WS_MSG_EVT_MASTER_JOINED_ROOM',
    MASTER_LEFT_ROOM: 'WS_MSG_EVT_MASTER_LEFT_ROOM',
    PLAYER_LEFT_ROOM: 'WS_MSG_EVT_PLAYER_LEFT_ROOM',
    PLAYER_JOIN_ROOM: 'WS_MSG_EVT_PLAYER_JOIN_ROOM',
    PLAYER_JOINED_ROOM: 'WS_MSG_EVT_PLAYER_JOINED_ROOM',
    PLAYER_JOIN_ROOM_RESPONSE: 'WS_MSG_EVT_PLAYER_JOIN_ROOM_RESPONSE',
    MASTER_JOIN_ROOM_RESPONSE: 'WS_MSG_EVT_MASTER_JOIN_ROOM_RESPONSE'
} as const;