name: CI

on: pull_request

jobs:
  build:
    name: "Test & Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run formatter
        run: pnpm run format

      - name: Run linter
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run test
        run: pnpm run test
