name: Client - Build 🏗️

on:
  push:
    branches: [ "main" ]
    paths: [ "client/**", "common/**", ".github/workflows/client-cd.yml" ]

jobs:      
  DeployOnCloudflare:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: NPM Install
      run: npm install
    
    - name: NPM Build
      run: npm run build
      env:
        VITE_SERVER_BASE_URL: ${{ secrets.VITE_SERVER_BASE_URL }}
        VITE_SERVER_BASE_WS_URL: ${{ secrets.VITE_SERVER_BASE_WS_URL }}
  
    - name: Deploy To Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 'ab30a017b87c1dcc6b925915c129206a'
        projectName: 'word-impostor'
        directory: './client/dist'
