name: PR Enforcement

on:
  pull_request:
    branches:
      - main
      - staging
      - release

jobs:
  enforce-pr-rules:
    name: "Enforce PR Rules"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR base branch
        run: |
          if [[ "${{ github.base_ref }}" == "staging" && "${{ github.head_ref }}" != "main" ]]; then
            echo "Pull requests to staging must come from main."
            exit 1
          elif [[ "${{ github.base_ref }}" == "release" && "${{ github.head_ref }}" != "staging" ]]; then
            echo "Pull requests to release must come from staging."
            exit 1
          elif [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" == "staging" ]]; then
            echo "Pull requests to main cannot come from staging."
            exit 1
          elif [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" == "release" ]]; then
            echo "Pull requests to main cannot come from release."
            exit 1
          elif [[ "${{ github.base_ref }}" == "staging" && "${{ github.head_ref }}" == "main" ]]; then
            echo "Pull requests to staging can come from main."
          elif [[ "${{ github.base_ref }}" == "release" && "${{ github.head_ref }}" == "staging" ]]; then
            echo "Pull requests to release can release from staging."
          elif [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "Pull requests to main can come from any branch."
          else
            echo "Invalid pull request base branch."
            exit 1
          fi
