name: Server - Build 🏗️

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  
on:
  push:
    branches: [ "main" ]
    paths: [ "server/**", "shared/**", ".github/workflows/server-cd.yml" ]

jobs:      
  DeployOnRender:
    runs-on: ubuntu-latest

    steps:        
    - name: Deploy To Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
